"""Small deterministic probing signals for closed-loop identification."""

from __future__ import annotations

from dataclasses import dataclass
import math

import numpy as np
from scipy.signal import max_len_seq


@dataclass(frozen=True)
class PRBSConfig:
    amplitude_sum_torque_nm: float
    start_time_s: float
    duration_s: float
    bit_period_s: float
    lfsr_bits: int
    seed: int


class CenteredPRBS:
    """Finite, exactly zero-mean PRBS schedule generated by SciPy's m-sequence."""

    def __init__(self, config: PRBSConfig):
        self.config = config
        bit_count = int(math.ceil(config.duration_s / config.bit_period_s))
        initial_state = np.array(
            [(config.seed >> bit) & 1 for bit in range(config.lfsr_bits)],
            dtype=np.int8,
        )
        if not np.any(initial_state):
            initial_state[0] = 1
        base, _ = max_len_seq(config.lfsr_bits, state=initial_state)
        raw = 2.0 * np.resize(base.astype(float), bit_count) - 1.0
        centered = raw - np.mean(raw)
        self._normalized_sequence = centered / np.max(np.abs(centered))

    @property
    def scheduled_mean_nm(self) -> float:
        return float(self.config.amplitude_sum_torque_nm * np.mean(self._normalized_sequence))

    @property
    def scheduled_rms_nm(self) -> float:
        return float(
            self.config.amplitude_sum_torque_nm
            * np.sqrt(np.mean(self._normalized_sequence**2))
        )

    def value(self, time_s: float) -> float:
        relative = time_s - self.config.start_time_s
        if relative < 0.0 or relative >= self.config.duration_s:
            return 0.0
        index = min(
            int(relative / self.config.bit_period_s),
            len(self._normalized_sequence) - 1,
        )
        return float(self.config.amplitude_sum_torque_nm * self._normalized_sequence[index])

    def is_active(self, time_s: float) -> bool:
        """Whether deliberate exogenous excitation is scheduled at this time."""

        relative = time_s - self.config.start_time_s
        return bool(0.0 <= relative < self.config.duration_s)
